<?php

/**
 * All constant define here which we are using in our whole system.
 */

return [
    'hotel_type' => [
	    1 => 'Hotels',
	    2 => 'Villas',
	    3 => 'Disney',
	    4 => 'Universal',
	    5 => 'Apartments',
	    6 => 'Guest House',
	    7 => 'Hostel',
	    8 => 'Aparthotel',
    ],
    'hotel_rating' =>[
    	1=>	1,
    	2=>	2,
    	3=>	3,
    	4=>	4,
    	5=>	5,
    ],
    'holiday_type' => [
	    1 => 'Package Holiday',
	    2 => 'Multi Center',
	    3 => 'Flight Vehicle',
	    4 => 'Cruse Stay',
	    5 => 'Accomodation Only',
    ],
    'cruse_line'=>[
    	1 => 'No prefernce',
	    2 => 'Best Offer',
	    3 => 'Royal Carribbean',
	    4 => 'Norwegian Cruise Line',
	    5 => 'Celebrity',
	    6 => 'Carnival',
	    7 => 'Disney Cruise',
	    8 => 'Other',
    ],
    'cabin_type'=>[
    	1 => 'No prefernce',
	    2 => 'Inside',
	    3 => 'Outside',
	    4 => 'Balcony',
	    5 => 'Suite',
    ],

    'destination_length'=>[
    	1 => '1 Night',
	    2 => '2 Nights',
	    3 => '3 Nights',
	    4 => '4 Nights',
	    5 => '5 Nights',
	    6 => '6 Nights',
	    7 => '7 Nights',
	    8 => '8 Nights',
	    9 => '9 Nights',
	    10 => '10 Nights',
	    11 => '11 Nights',
	    12 => '12 Nights',
	    13 => '13 Nights',
	    14 => '14 Nights',
	    15 => '15 Nights',
	    16 => '16 Nights',
	    17 => '17 Nights',
	    18 => '18 Nights',
	    19 => '19 Nights',
	    20 => '20 Nights',
	    22 => '22 Nights',
	    23 => '23 Nights',
	    24 => '24 Nights',
	    25 => '25 Nights',
	    26 => '26 Nights',
    ],

    'vehicle_type'=>[
    	1 => 'Economy 2/4 door',
	    2 => 'Compact 2/4 door',
	    3 => 'Standard 2/4 door',
	    4 => 'Full size 2/4 door',
	    5 => 'Intermidiate 2/4 door',
	    6 => 'Premium 2/4 door',
	    7 => 'Convertible 2',
	    8 => 'Itermidiate Suv',
    ],
    'cruse_destination'=>[
    	1 => 'Alaska',
	    2 => 'Bahamas',
	    3 => 'Canada',
	    4 => 'Caribbean',
	    5 => 'Hawaii',
	    6 => 'Mexico',
	    7 => 'New England',
	    8 => 'Panama Canal',
    ], 
    'flexible_date_type'=>[
    	1 => 'Flexibility +/-',
	    2 => 'I am not flexible',
	    3 => '+/- 1 day',
	    4 => '+/- 2 day',
	    5 => '+/- 3 day',
	    6 => '+/- 4 day',
	    7 => '+/- 5 day',
	    9 => '+/- 6 day',
	    10 => '+/- 7 day',
	    11 => '+/- 8 day',
	    12 => '+/- 9 day',
	    13 => '+/- 10 day',
	    14 => '+/- 11 day',
	    15 => '+/- 12 day',
	    16 => '+/- 13 day',
	    17 => '+/- 14 day',
	    18 => '+/- 15 day',
    ],
    'departure_airport'=>[
    	1 => 'Belfast',
	    2 => 'Birmingham',
	    3 => 'Briston',
	    4 => 'Dublin',
    ],

    'transport_req'=>[
    	1 => 'None require',
	    2 => 'Return Transfers',
	    3 => 'Fully Comp Car Hire',
    ],
    'no_adults'=>[
    	1 => '1 Adult',
	    2 => '2 Adults',
	    3 => '3 Adults',
	    4 => '4 Adults',
	    5 => '5 Adults',
	    6 => '6 Adults',
	    7 => '7 Adults',
	    8 => '8 Adults',
	    9 => '9 Adults',
	    10 => '10 Adults',
	    11 => '11 Adults',
	    12 => '12 Adults',
	    13 => '13 Adults',
	    14 => '14 Adults',
	    15 => '15 Adults',
	    16 => '16 Adults',
	    17 => '17 Adults',
	    18 => '18 Adults',
	    19 => '19 Adults',
	    20 => '20 Adults',
    ],
    'no_children'=>[
    	0 => 'None',
    	1 => '1 Child',
	    2 => '2 Children',
	    3 => '3 Children',
	    4 => '4 Children',
	    5 => '5 Children',
	    6 => '6 Children',
	    7 => '7 Children',
	    8 => '8 Children',
	    9 => '9 Children',
	    10 => '10 Children',
	    11 => '11 Children',
	    12 => '12 Children',
	    13 => '13 Children',
	    14 => '14 Children',
	    15 => '15 Children',
	    16 => '16 Children',
	    17 => '17 Children',
	    18 => '18 Children',
	    19 => '19 Children',
	    20 => '20 Children',
    ],
    'no_infants'=>[
    	0 => 'None',
    	1 => '1 infant',
	    2 => '2 Infants',
	    3 => '3 Infants',
	    4 => '4 Infants',
	    5 => '5 Infants',
	    6 => '6 Infants',
	    7 => '7 Infants',
	    8 => '8 Infants',
	    9 => '9 Infants',
	    10 => '10 Infants',
	    11 => '11 Infants',
	    12 => '12 Infants',
	    13 => '13 Infants',
	    14 => '14 Infants',
	    15 => '15 Infants',
	    16 => '16 Infants',
	    17 => '17 Infants',
	    18 => '18 Infants',
	    19 => '19 Infants',
	    20 => '20 Infants',
    ],

];